//MikanBot Discord Utilities
//Licenced to KuronekoServer under the MIT License
//© 2023 MikanDev All Rights Reserved

module.exports = {
    AddReactions: "Add Reactions",
    Administrator: "Administrator",
    AttachFiles: "Attach files",
    BanMembers: "Ban members",
    ChangeNickname: "Change nickname",
    Connect: "Connect",
    CreateInstantInvite: "Create instant invite",
    CreatePrivateThreads: "Create private threads",
    CreatePublicThreads: "Create public threads",
    DeafenMembers: "Deafen members",
    EmbedLinks: "Embed links",
    KickMembers: "Kick members",
    ManageChannels: "Manage channels",
    ManageEmojisAndStickers: "Manage emojis and stickers",
    ManageEvents: "Manage Events",
    ManageGuild: "Manage server",
    ManageMessages: "Manage messages",
    ManageNicknames: "Manage nicknames",
    ManageRoles: "Manage roles",
    ManageThreads: "Manage Threads",
    ManageWebhooks: "Manage webhooks",
    MentionEveryone: "Mention everyone",
    ModerateMembers: "Moderate Members",
    MoveMembers: "Move members",
    MuteMembers: "Mute members",
    PrioritySpeaker: "Priority speaker",
    ReadMessageHistory: "Read message history",
    RequestToSpeak: "Request to Speak",
    SendMessages: "Send messages",
    SendMessagesInThreads: "Send Messages In Threads",
    SendTTSMessages: "Send TTS messages",
    Speak: "Speak",
    Stream: "Video",
    UseApplicationCommands: "Use Application Commands",
    UseEmbeddedActivities: "Use Embedded Activities",
    UseExternalEmojis: "Use External Emojis",
    UseExternalStickers: "Use External Stickers",
    UseVAD: "Use voice activity",
    ViewAuditLog: "View audit log",
    ViewChannel: "View channel",
    ViewGuildInsights: "View server insights",
    UseSoundboard: "Use Soundboard",
    SendVoiceMessages: "Send Voice Messages",
    ja: {
        AddReactions: "リアクションの追加",
        Administrator: "管理者",
        AttachFiles: "ファイルを添付",
        BanMembers: "メンバーをBAN",
        ChangeNickname: "ニックネームの変更",
        Connect: "接続",
        CreateInstantInvite: "招待を作成",
        CreatePrivateThreads: "プライベートスレッドの作成",
        CreatePublicThreads: "公開スレッドの作成",
        DeafenMembers: "メンバーのスピーカーをミュート",
        EmbedLinks: "埋め込みリンク",
        KickMembers: "メンバーをキック",
        ManageChannels: "チャンネルの管理",
        ManageEmojisAndStickers: "絵文字・スタンプの管理",
        ManageEvents: "イベントの管理",
        ManageGuild: "サーバーの管理",
        ManageMessages: "メッセージの管理",
        ManageNicknames: "ニックネームの管理",
        ManageRoles: "ロールの管理",
        ManageThreads: "スレッドの管理",
        ManageWebhooks: "ウェブフックの管理",
        MentionEveryone: "@everyone、@here、すべてのロールにメンション",
        ModerateMembers: "メンバーの管理",
        MoveMembers: "メンバーを移動",
        MuteMembers: "メンバーをミュート",
        PrioritySpeaker: "優先スピーカー",
        ReadMessageHistory: "メッセージ履歴を読む",
        RequestToSpeak: "音声検出を使用",
        SendMessages: "メッセージを送信",
        SendMessagesInThreads: "スレッドでメッセージを送信",
        SendTTSMessages: "Send TTS messages",
        Speak: "発言",
        Stream: "WEBカメラ",
        UseApplicationCommands: "アプリコマンドを使う",
        UseEmbeddedActivities: "Use Embedded Activities",
        UseExternalEmojis: "外部絵文字を使用する",
        UseExternalStickers: "外部スタンプを使用する",
        UseVAD: "ユーザーアクティビティ",
        ViewAuditLog: "監視ログを表示",
        ViewChannel: "チャンネルを見る",
        ViewGuildInsights: "サーバーインサイトを見る",
        UseSoundboard: "サウンドボードを使用する",
        SendVoiceMessages: "ボイスメッセージを送信する"
    }
};